//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Försäkring> FörsäkringSet { get; set; }
        public virtual DbSet<Personal> PersonalSet { get; set; }
        public virtual DbSet<Företagsansökan> FöretagsansökanSet { get; set; }
        public virtual DbSet<Privatansökan> PrivatansökanSet { get; set; }
        public virtual DbSet<FörsäkringstagarePrivat> FörsäkringstagarePrivatSet { get; set; }
        public virtual DbSet<FörsäkringstagareFöretag> FörsäkringstagareFöretagSet { get; set; }
        public virtual DbSet<Roll> RollSet { get; set; }
        public virtual DbSet<Behörighet> BehörighetSet { get; set; }
        public virtual DbSet<Tillval> TillvalSet { get; set; }
        public virtual DbSet<TillvalGrundbelopp> TillvalGrundbeloppSet { get; set; }
        public virtual DbSet<Provisionstabell> ProvisionstabellSet { get; set; }
        public virtual DbSet<Semesterersättning> SemesterersättningSet { get; set; }
        public virtual DbSet<Grundbelopp> GrundbeloppSet { get; set; }
        public virtual DbSet<FörsäkringsTyp> FörsäkringsTypSet { get; set; }
        public virtual DbSet<FörsäkringFöretag> FörsäkringFöretagSet { get; set; }
    }
}
