//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FörsäkringstagareFöretag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FörsäkringstagareFöretag()
        {
            this.Företagsansökan = new HashSet<Företagsansökan>();
        }
    
        public long försäkringstagareFöretagId { get; set; }
        public string företagsNamn { get; set; }
        public string kFNamn { get; set; }
        public string kENamn { get; set; }
        public string ort { get; set; }
        public int postNr { get; set; }
        public int tel1 { get; set; }
        public int faxNr { get; set; }
        public string email1 { get; set; }
        public string gatuAdress { get; set; }
        public long orgNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Företagsansökan> Företagsansökan { get; set; }
    }
}
