//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Företagsansökan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Företagsansökan()
        {
            this.FörsäkringFöretag = new HashSet<FörsäkringFöretag>();
        }
    
        public int företagsAnsökningsId { get; set; }
        public string försäkringsbolag { get; set; }
        public System.DateTime begynnelsedatum { get; set; }
        public System.DateTime förfallodag { get; set; }
        public string betalningsform { get; set; }
        public int premie { get; set; }
        public string Anteckning { get; set; }
        public string försäkringsTyp { get; set; }
    
        public virtual FörsäkringstagareFöretag FörsäkringstagareFöretag { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FörsäkringFöretag> FörsäkringFöretag { get; set; }
    }
}
