//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Försäkring
    {
        public int försäkringsId { get; set; }
        public string försäkringsNr { get; set; }
        public System.DateTime betald { get; set; }
        public Nullable<int> provisionsbelopp { get; set; }
    
        public virtual Privatansökan Privatansökan { get; set; }
    }
}
