//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grundbelopp
    {
        public int grundbeloppsId { get; set; }
        public System.DateTime datum { get; set; }
        public int grundBelopp { get; set; }
        public double ackVärde { get; set; }
    
        public virtual FörsäkringsTyp FörsäkringsTyp { get; set; }
    }
}
