//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privatansökan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Privatansökan()
        {
            this.Försäkring = new HashSet<Försäkring>();
        }
    
        public int privatAnsökningsId { get; set; }
        public long privatFörsäkradPersNr { get; set; }
        public string privatFörsäkradENamn { get; set; }
        public string privatFörsäkradFNamn { get; set; }
        public System.DateTime ankomstdatum { get; set; }
        public string betalningsform { get; set; }
        public string vuxen { get; set; }
        public int premie { get; set; }
        public string paGatuadress { get; set; }
        public string paOrt { get; set; }
        public int paPostnr { get; set; }
        public string tillvalsNamn { get; set; }
        public int grundBelopp { get; set; }
        public Nullable<int> tvGrundbelopp { get; set; }
        public string försäkringsbolag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Försäkring> Försäkring { get; set; }
        public virtual FörsäkringstagarePrivat FörsäkringstagarePrivat { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual FörsäkringsTyp FörsäkringsTyp { get; set; }
    }
}
