//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provisionstabell
    {
        public int provisionstabellsId { get; set; }
        public int totaltMinAckVärde { get; set; }
        public int totaltMaxAckVärde { get; set; }
        public double provisionsAndelBarn { get; set; }
        public double provionsAndelVuxen { get; set; }
        public string period { get; set; }
    }
}
