//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tillval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tillval()
        {
            this.TillvalGrundbelopp = new HashSet<TillvalGrundbelopp>();
            this.FörsäkringsTyp = new HashSet<FörsäkringsTyp>();
        }
    
        public int tillvalsId { get; set; }
        public System.DateTime datum { get; set; }
        public double ackVärdeVariabel { get; set; }
        public string tillvalsNamn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TillvalGrundbelopp> TillvalGrundbelopp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FörsäkringsTyp> FörsäkringsTyp { get; set; }
    }
}
